package com.opvita.activity.dto;

import java.math.BigDecimal;
import java.util.Date;

public class EsOrderDTO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER.ORDER_ID
     *
     * @mbggenerated
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER.SN
     *
     * @mbggenerated
     */
    private String sn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER.MEMBER_ID
     *
     * @mbggenerated
     */
    private Integer memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER.SHIPPING_ID
     *
     * @mbggenerated
     */
    private Integer shippingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER.SHIPPING_TYPE
     *
     * @mbggenerated
     */
    private String shippingType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER.SHIPPING_AREA
     *
     * @mbggenerated
     */
    private String shippingArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER.PAYMENT_ID
     *
     * @mbggenerated
     */
    private Integer paymentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER.PAYMENT_NAME
     *
     * @mbggenerated
     */
    private String paymentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER.PAYMENT_TYPE
     *
     * @mbggenerated
     */
    private String paymentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER.PAYMONEY
     *
     * @mbggenerated
     */
    private BigDecimal paymoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER.SHIP_NAME
     *
     * @mbggenerated
     */
    private String shipName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER.SHIP_ADDR
     *
     * @mbggenerated
     */
    private String shipAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER.SHIP_ZIP
     *
     * @mbggenerated
     */
    private String shipZip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER.SHIP_EMAIL
     *
     * @mbggenerated
     */
    private String shipEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER.SHIP_MOBILE
     *
     * @mbggenerated
     */
    private String shipMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER.SHIP_TEL
     *
     * @mbggenerated
     */
    private String shipTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER.SHIP_DAY
     *
     * @mbggenerated
     */
    private String shipDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER.IS_PROTECT
     *
     * @mbggenerated
     */
    private String isProtect;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER.PROTECT_PRICE
     *
     * @mbggenerated
     */
    private BigDecimal protectPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER.GOODS_AMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal goodsAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER.SHIPPING_AMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal shippingAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER.ORDER_AMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal orderAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER.WEIGHT
     *
     * @mbggenerated
     */
    private BigDecimal weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER.GOODS_NUM
     *
     * @mbggenerated
     */
    private Integer goodsNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER.GAINEDPOINT
     *
     * @mbggenerated
     */
    private Long gainedpoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER.CONSUMEPOINT
     *
     * @mbggenerated
     */
    private Long consumepoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER.DISCOUNT
     *
     * @mbggenerated
     */
    private BigDecimal discount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER.IMPORTED
     *
     * @mbggenerated
     */
    private Short imported;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER.PIMPORTED
     *
     * @mbggenerated
     */
    private Short pimported;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER.CANCEL_REASON
     *
     * @mbggenerated
     */
    private String cancelReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER.THE_SIGN
     *
     * @mbggenerated
     */
    private String theSign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER.SHIP_PROVINCEID
     *
     * @mbggenerated
     */
    private Long shipProvinceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER.SHIP_CITYID
     *
     * @mbggenerated
     */
    private Long shipCityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER.SHIP_REGIONID
     *
     * @mbggenerated
     */
    private Long shipRegionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER.SALE_CMPL
     *
     * @mbggenerated
     */
    private Short saleCmpl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER.DEPOTID
     *
     * @mbggenerated
     */
    private Long depotid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER.ADMIN_REMARK
     *
     * @mbggenerated
     */
    private String adminRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER.ALLOCATION_TIME
     *
     * @mbggenerated
     */
    private Date allocationTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER.COMPLETE_TIME
     *
     * @mbggenerated
     */
    private Date completeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER.SALE_CMPL_TIME
     *
     * @mbggenerated
     */
    private Date saleCmplTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER.SHIP_TIME
     *
     * @mbggenerated
     */
    private Date shipTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER.SIGNING_TIME
     *
     * @mbggenerated
     */
    private Date signingTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER.ORDER_STATUS
     *
     * @mbggenerated
     */
    private String orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER.PAY_STATUS
     *
     * @mbggenerated
     */
    private String payStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER.SHIP_STATUS
     *
     * @mbggenerated
     */
    private String shipStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER.ISSUER_ID
     *
     * @mbggenerated
     */
    private String issuerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER.PAY_CHANNEL
     *
     * @mbggenerated
     */
    private String payChannel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER.PAY_BILL_NO
     *
     * @mbggenerated
     */
    private String payBillNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER.BUYER_MOBILE
     *
     * @mbggenerated
     */
    private String buyerMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER.SENDER_NAME
     *
     * @mbggenerated
     */
    private String senderName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER.SEND_WORD
     *
     * @mbggenerated
     */
    private String sendWord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER.EO_TYPE
     *
     * @mbggenerated
     */
    private String eoType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER.CUST_SEQ
     *
     * @mbggenerated
     */
    private String custSeq;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER.ORDER_ID
     *
     * @return the value of CULSITE.ES_ORDER.ORDER_ID
     *
     * @mbggenerated
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER.ORDER_ID
     *
     * @param orderId the value for CULSITE.ES_ORDER.ORDER_ID
     *
     * @mbggenerated
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER.SN
     *
     * @return the value of CULSITE.ES_ORDER.SN
     *
     * @mbggenerated
     */
    public String getSn() {
        return sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER.SN
     *
     * @param sn the value for CULSITE.ES_ORDER.SN
     *
     * @mbggenerated
     */
    public void setSn(String sn) {
        this.sn = sn == null ? null : sn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER.MEMBER_ID
     *
     * @return the value of CULSITE.ES_ORDER.MEMBER_ID
     *
     * @mbggenerated
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER.MEMBER_ID
     *
     * @param memberId the value for CULSITE.ES_ORDER.MEMBER_ID
     *
     * @mbggenerated
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER.SHIPPING_ID
     *
     * @return the value of CULSITE.ES_ORDER.SHIPPING_ID
     *
     * @mbggenerated
     */
    public Integer getShippingId() {
        return shippingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER.SHIPPING_ID
     *
     * @param shippingId the value for CULSITE.ES_ORDER.SHIPPING_ID
     *
     * @mbggenerated
     */
    public void setShippingId(Integer shippingId) {
        this.shippingId = shippingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER.SHIPPING_TYPE
     *
     * @return the value of CULSITE.ES_ORDER.SHIPPING_TYPE
     *
     * @mbggenerated
     */
    public String getShippingType() {
        return shippingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER.SHIPPING_TYPE
     *
     * @param shippingType the value for CULSITE.ES_ORDER.SHIPPING_TYPE
     *
     * @mbggenerated
     */
    public void setShippingType(String shippingType) {
        this.shippingType = shippingType == null ? null : shippingType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER.SHIPPING_AREA
     *
     * @return the value of CULSITE.ES_ORDER.SHIPPING_AREA
     *
     * @mbggenerated
     */
    public String getShippingArea() {
        return shippingArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER.SHIPPING_AREA
     *
     * @param shippingArea the value for CULSITE.ES_ORDER.SHIPPING_AREA
     *
     * @mbggenerated
     */
    public void setShippingArea(String shippingArea) {
        this.shippingArea = shippingArea == null ? null : shippingArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER.PAYMENT_ID
     *
     * @return the value of CULSITE.ES_ORDER.PAYMENT_ID
     *
     * @mbggenerated
     */
    public Integer getPaymentId() {
        return paymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER.PAYMENT_ID
     *
     * @param paymentId the value for CULSITE.ES_ORDER.PAYMENT_ID
     *
     * @mbggenerated
     */
    public void setPaymentId(Integer paymentId) {
        this.paymentId = paymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER.PAYMENT_NAME
     *
     * @return the value of CULSITE.ES_ORDER.PAYMENT_NAME
     *
     * @mbggenerated
     */
    public String getPaymentName() {
        return paymentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER.PAYMENT_NAME
     *
     * @param paymentName the value for CULSITE.ES_ORDER.PAYMENT_NAME
     *
     * @mbggenerated
     */
    public void setPaymentName(String paymentName) {
        this.paymentName = paymentName == null ? null : paymentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER.PAYMENT_TYPE
     *
     * @return the value of CULSITE.ES_ORDER.PAYMENT_TYPE
     *
     * @mbggenerated
     */
    public String getPaymentType() {
        return paymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER.PAYMENT_TYPE
     *
     * @param paymentType the value for CULSITE.ES_ORDER.PAYMENT_TYPE
     *
     * @mbggenerated
     */
    public void setPaymentType(String paymentType) {
        this.paymentType = paymentType == null ? null : paymentType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER.PAYMONEY
     *
     * @return the value of CULSITE.ES_ORDER.PAYMONEY
     *
     * @mbggenerated
     */
    public BigDecimal getPaymoney() {
        return paymoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER.PAYMONEY
     *
     * @param paymoney the value for CULSITE.ES_ORDER.PAYMONEY
     *
     * @mbggenerated
     */
    public void setPaymoney(BigDecimal paymoney) {
        this.paymoney = paymoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER.SHIP_NAME
     *
     * @return the value of CULSITE.ES_ORDER.SHIP_NAME
     *
     * @mbggenerated
     */
    public String getShipName() {
        return shipName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER.SHIP_NAME
     *
     * @param shipName the value for CULSITE.ES_ORDER.SHIP_NAME
     *
     * @mbggenerated
     */
    public void setShipName(String shipName) {
        this.shipName = shipName == null ? null : shipName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER.SHIP_ADDR
     *
     * @return the value of CULSITE.ES_ORDER.SHIP_ADDR
     *
     * @mbggenerated
     */
    public String getShipAddr() {
        return shipAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER.SHIP_ADDR
     *
     * @param shipAddr the value for CULSITE.ES_ORDER.SHIP_ADDR
     *
     * @mbggenerated
     */
    public void setShipAddr(String shipAddr) {
        this.shipAddr = shipAddr == null ? null : shipAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER.SHIP_ZIP
     *
     * @return the value of CULSITE.ES_ORDER.SHIP_ZIP
     *
     * @mbggenerated
     */
    public String getShipZip() {
        return shipZip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER.SHIP_ZIP
     *
     * @param shipZip the value for CULSITE.ES_ORDER.SHIP_ZIP
     *
     * @mbggenerated
     */
    public void setShipZip(String shipZip) {
        this.shipZip = shipZip == null ? null : shipZip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER.SHIP_EMAIL
     *
     * @return the value of CULSITE.ES_ORDER.SHIP_EMAIL
     *
     * @mbggenerated
     */
    public String getShipEmail() {
        return shipEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER.SHIP_EMAIL
     *
     * @param shipEmail the value for CULSITE.ES_ORDER.SHIP_EMAIL
     *
     * @mbggenerated
     */
    public void setShipEmail(String shipEmail) {
        this.shipEmail = shipEmail == null ? null : shipEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER.SHIP_MOBILE
     *
     * @return the value of CULSITE.ES_ORDER.SHIP_MOBILE
     *
     * @mbggenerated
     */
    public String getShipMobile() {
        return shipMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER.SHIP_MOBILE
     *
     * @param shipMobile the value for CULSITE.ES_ORDER.SHIP_MOBILE
     *
     * @mbggenerated
     */
    public void setShipMobile(String shipMobile) {
        this.shipMobile = shipMobile == null ? null : shipMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER.SHIP_TEL
     *
     * @return the value of CULSITE.ES_ORDER.SHIP_TEL
     *
     * @mbggenerated
     */
    public String getShipTel() {
        return shipTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER.SHIP_TEL
     *
     * @param shipTel the value for CULSITE.ES_ORDER.SHIP_TEL
     *
     * @mbggenerated
     */
    public void setShipTel(String shipTel) {
        this.shipTel = shipTel == null ? null : shipTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER.SHIP_DAY
     *
     * @return the value of CULSITE.ES_ORDER.SHIP_DAY
     *
     * @mbggenerated
     */
    public String getShipDay() {
        return shipDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER.SHIP_DAY
     *
     * @param shipDay the value for CULSITE.ES_ORDER.SHIP_DAY
     *
     * @mbggenerated
     */
    public void setShipDay(String shipDay) {
        this.shipDay = shipDay == null ? null : shipDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER.IS_PROTECT
     *
     * @return the value of CULSITE.ES_ORDER.IS_PROTECT
     *
     * @mbggenerated
     */
    public String getIsProtect() {
        return isProtect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER.IS_PROTECT
     *
     * @param isProtect the value for CULSITE.ES_ORDER.IS_PROTECT
     *
     * @mbggenerated
     */
    public void setIsProtect(String isProtect) {
        this.isProtect = isProtect == null ? null : isProtect.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER.PROTECT_PRICE
     *
     * @return the value of CULSITE.ES_ORDER.PROTECT_PRICE
     *
     * @mbggenerated
     */
    public BigDecimal getProtectPrice() {
        return protectPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER.PROTECT_PRICE
     *
     * @param protectPrice the value for CULSITE.ES_ORDER.PROTECT_PRICE
     *
     * @mbggenerated
     */
    public void setProtectPrice(BigDecimal protectPrice) {
        this.protectPrice = protectPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER.GOODS_AMOUNT
     *
     * @return the value of CULSITE.ES_ORDER.GOODS_AMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getGoodsAmount() {
        return goodsAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER.GOODS_AMOUNT
     *
     * @param goodsAmount the value for CULSITE.ES_ORDER.GOODS_AMOUNT
     *
     * @mbggenerated
     */
    public void setGoodsAmount(BigDecimal goodsAmount) {
        this.goodsAmount = goodsAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER.SHIPPING_AMOUNT
     *
     * @return the value of CULSITE.ES_ORDER.SHIPPING_AMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getShippingAmount() {
        return shippingAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER.SHIPPING_AMOUNT
     *
     * @param shippingAmount the value for CULSITE.ES_ORDER.SHIPPING_AMOUNT
     *
     * @mbggenerated
     */
    public void setShippingAmount(BigDecimal shippingAmount) {
        this.shippingAmount = shippingAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER.ORDER_AMOUNT
     *
     * @return the value of CULSITE.ES_ORDER.ORDER_AMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getOrderAmount() {
        return orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER.ORDER_AMOUNT
     *
     * @param orderAmount the value for CULSITE.ES_ORDER.ORDER_AMOUNT
     *
     * @mbggenerated
     */
    public void setOrderAmount(BigDecimal orderAmount) {
        this.orderAmount = orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER.WEIGHT
     *
     * @return the value of CULSITE.ES_ORDER.WEIGHT
     *
     * @mbggenerated
     */
    public BigDecimal getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER.WEIGHT
     *
     * @param weight the value for CULSITE.ES_ORDER.WEIGHT
     *
     * @mbggenerated
     */
    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER.GOODS_NUM
     *
     * @return the value of CULSITE.ES_ORDER.GOODS_NUM
     *
     * @mbggenerated
     */
    public Integer getGoodsNum() {
        return goodsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER.GOODS_NUM
     *
     * @param goodsNum the value for CULSITE.ES_ORDER.GOODS_NUM
     *
     * @mbggenerated
     */
    public void setGoodsNum(Integer goodsNum) {
        this.goodsNum = goodsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER.GAINEDPOINT
     *
     * @return the value of CULSITE.ES_ORDER.GAINEDPOINT
     *
     * @mbggenerated
     */
    public Long getGainedpoint() {
        return gainedpoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER.GAINEDPOINT
     *
     * @param gainedpoint the value for CULSITE.ES_ORDER.GAINEDPOINT
     *
     * @mbggenerated
     */
    public void setGainedpoint(Long gainedpoint) {
        this.gainedpoint = gainedpoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER.CONSUMEPOINT
     *
     * @return the value of CULSITE.ES_ORDER.CONSUMEPOINT
     *
     * @mbggenerated
     */
    public Long getConsumepoint() {
        return consumepoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER.CONSUMEPOINT
     *
     * @param consumepoint the value for CULSITE.ES_ORDER.CONSUMEPOINT
     *
     * @mbggenerated
     */
    public void setConsumepoint(Long consumepoint) {
        this.consumepoint = consumepoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER.STATUS
     *
     * @return the value of CULSITE.ES_ORDER.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER.STATUS
     *
     * @param status the value for CULSITE.ES_ORDER.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER.DISCOUNT
     *
     * @return the value of CULSITE.ES_ORDER.DISCOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER.DISCOUNT
     *
     * @param discount the value for CULSITE.ES_ORDER.DISCOUNT
     *
     * @mbggenerated
     */
    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER.IMPORTED
     *
     * @return the value of CULSITE.ES_ORDER.IMPORTED
     *
     * @mbggenerated
     */
    public Short getImported() {
        return imported;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER.IMPORTED
     *
     * @param imported the value for CULSITE.ES_ORDER.IMPORTED
     *
     * @mbggenerated
     */
    public void setImported(Short imported) {
        this.imported = imported;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER.PIMPORTED
     *
     * @return the value of CULSITE.ES_ORDER.PIMPORTED
     *
     * @mbggenerated
     */
    public Short getPimported() {
        return pimported;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER.PIMPORTED
     *
     * @param pimported the value for CULSITE.ES_ORDER.PIMPORTED
     *
     * @mbggenerated
     */
    public void setPimported(Short pimported) {
        this.pimported = pimported;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER.CANCEL_REASON
     *
     * @return the value of CULSITE.ES_ORDER.CANCEL_REASON
     *
     * @mbggenerated
     */
    public String getCancelReason() {
        return cancelReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER.CANCEL_REASON
     *
     * @param cancelReason the value for CULSITE.ES_ORDER.CANCEL_REASON
     *
     * @mbggenerated
     */
    public void setCancelReason(String cancelReason) {
        this.cancelReason = cancelReason == null ? null : cancelReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER.THE_SIGN
     *
     * @return the value of CULSITE.ES_ORDER.THE_SIGN
     *
     * @mbggenerated
     */
    public String getTheSign() {
        return theSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER.THE_SIGN
     *
     * @param theSign the value for CULSITE.ES_ORDER.THE_SIGN
     *
     * @mbggenerated
     */
    public void setTheSign(String theSign) {
        this.theSign = theSign == null ? null : theSign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER.SHIP_PROVINCEID
     *
     * @return the value of CULSITE.ES_ORDER.SHIP_PROVINCEID
     *
     * @mbggenerated
     */
    public Long getShipProvinceid() {
        return shipProvinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER.SHIP_PROVINCEID
     *
     * @param shipProvinceid the value for CULSITE.ES_ORDER.SHIP_PROVINCEID
     *
     * @mbggenerated
     */
    public void setShipProvinceid(Long shipProvinceid) {
        this.shipProvinceid = shipProvinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER.SHIP_CITYID
     *
     * @return the value of CULSITE.ES_ORDER.SHIP_CITYID
     *
     * @mbggenerated
     */
    public Long getShipCityid() {
        return shipCityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER.SHIP_CITYID
     *
     * @param shipCityid the value for CULSITE.ES_ORDER.SHIP_CITYID
     *
     * @mbggenerated
     */
    public void setShipCityid(Long shipCityid) {
        this.shipCityid = shipCityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER.SHIP_REGIONID
     *
     * @return the value of CULSITE.ES_ORDER.SHIP_REGIONID
     *
     * @mbggenerated
     */
    public Long getShipRegionid() {
        return shipRegionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER.SHIP_REGIONID
     *
     * @param shipRegionid the value for CULSITE.ES_ORDER.SHIP_REGIONID
     *
     * @mbggenerated
     */
    public void setShipRegionid(Long shipRegionid) {
        this.shipRegionid = shipRegionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER.SALE_CMPL
     *
     * @return the value of CULSITE.ES_ORDER.SALE_CMPL
     *
     * @mbggenerated
     */
    public Short getSaleCmpl() {
        return saleCmpl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER.SALE_CMPL
     *
     * @param saleCmpl the value for CULSITE.ES_ORDER.SALE_CMPL
     *
     * @mbggenerated
     */
    public void setSaleCmpl(Short saleCmpl) {
        this.saleCmpl = saleCmpl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER.DEPOTID
     *
     * @return the value of CULSITE.ES_ORDER.DEPOTID
     *
     * @mbggenerated
     */
    public Long getDepotid() {
        return depotid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER.DEPOTID
     *
     * @param depotid the value for CULSITE.ES_ORDER.DEPOTID
     *
     * @mbggenerated
     */
    public void setDepotid(Long depotid) {
        this.depotid = depotid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER.ADMIN_REMARK
     *
     * @return the value of CULSITE.ES_ORDER.ADMIN_REMARK
     *
     * @mbggenerated
     */
    public String getAdminRemark() {
        return adminRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER.ADMIN_REMARK
     *
     * @param adminRemark the value for CULSITE.ES_ORDER.ADMIN_REMARK
     *
     * @mbggenerated
     */
    public void setAdminRemark(String adminRemark) {
        this.adminRemark = adminRemark == null ? null : adminRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER.CREATE_TIME
     *
     * @return the value of CULSITE.ES_ORDER.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER.CREATE_TIME
     *
     * @param createTime the value for CULSITE.ES_ORDER.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER.ALLOCATION_TIME
     *
     * @return the value of CULSITE.ES_ORDER.ALLOCATION_TIME
     *
     * @mbggenerated
     */
    public Date getAllocationTime() {
        return allocationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER.ALLOCATION_TIME
     *
     * @param allocationTime the value for CULSITE.ES_ORDER.ALLOCATION_TIME
     *
     * @mbggenerated
     */
    public void setAllocationTime(Date allocationTime) {
        this.allocationTime = allocationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER.COMPLETE_TIME
     *
     * @return the value of CULSITE.ES_ORDER.COMPLETE_TIME
     *
     * @mbggenerated
     */
    public Date getCompleteTime() {
        return completeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER.COMPLETE_TIME
     *
     * @param completeTime the value for CULSITE.ES_ORDER.COMPLETE_TIME
     *
     * @mbggenerated
     */
    public void setCompleteTime(Date completeTime) {
        this.completeTime = completeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER.SALE_CMPL_TIME
     *
     * @return the value of CULSITE.ES_ORDER.SALE_CMPL_TIME
     *
     * @mbggenerated
     */
    public Date getSaleCmplTime() {
        return saleCmplTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER.SALE_CMPL_TIME
     *
     * @param saleCmplTime the value for CULSITE.ES_ORDER.SALE_CMPL_TIME
     *
     * @mbggenerated
     */
    public void setSaleCmplTime(Date saleCmplTime) {
        this.saleCmplTime = saleCmplTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER.SHIP_TIME
     *
     * @return the value of CULSITE.ES_ORDER.SHIP_TIME
     *
     * @mbggenerated
     */
    public Date getShipTime() {
        return shipTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER.SHIP_TIME
     *
     * @param shipTime the value for CULSITE.ES_ORDER.SHIP_TIME
     *
     * @mbggenerated
     */
    public void setShipTime(Date shipTime) {
        this.shipTime = shipTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER.SIGNING_TIME
     *
     * @return the value of CULSITE.ES_ORDER.SIGNING_TIME
     *
     * @mbggenerated
     */
    public Date getSigningTime() {
        return signingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER.SIGNING_TIME
     *
     * @param signingTime the value for CULSITE.ES_ORDER.SIGNING_TIME
     *
     * @mbggenerated
     */
    public void setSigningTime(Date signingTime) {
        this.signingTime = signingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER.ORDER_STATUS
     *
     * @return the value of CULSITE.ES_ORDER.ORDER_STATUS
     *
     * @mbggenerated
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER.ORDER_STATUS
     *
     * @param orderStatus the value for CULSITE.ES_ORDER.ORDER_STATUS
     *
     * @mbggenerated
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus == null ? null : orderStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER.PAY_STATUS
     *
     * @return the value of CULSITE.ES_ORDER.PAY_STATUS
     *
     * @mbggenerated
     */
    public String getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER.PAY_STATUS
     *
     * @param payStatus the value for CULSITE.ES_ORDER.PAY_STATUS
     *
     * @mbggenerated
     */
    public void setPayStatus(String payStatus) {
        this.payStatus = payStatus == null ? null : payStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER.SHIP_STATUS
     *
     * @return the value of CULSITE.ES_ORDER.SHIP_STATUS
     *
     * @mbggenerated
     */
    public String getShipStatus() {
        return shipStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER.SHIP_STATUS
     *
     * @param shipStatus the value for CULSITE.ES_ORDER.SHIP_STATUS
     *
     * @mbggenerated
     */
    public void setShipStatus(String shipStatus) {
        this.shipStatus = shipStatus == null ? null : shipStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER.ISSUER_ID
     *
     * @return the value of CULSITE.ES_ORDER.ISSUER_ID
     *
     * @mbggenerated
     */
    public String getIssuerId() {
        return issuerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER.ISSUER_ID
     *
     * @param issuerId the value for CULSITE.ES_ORDER.ISSUER_ID
     *
     * @mbggenerated
     */
    public void setIssuerId(String issuerId) {
        this.issuerId = issuerId == null ? null : issuerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER.PAY_CHANNEL
     *
     * @return the value of CULSITE.ES_ORDER.PAY_CHANNEL
     *
     * @mbggenerated
     */
    public String getPayChannel() {
        return payChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER.PAY_CHANNEL
     *
     * @param payChannel the value for CULSITE.ES_ORDER.PAY_CHANNEL
     *
     * @mbggenerated
     */
    public void setPayChannel(String payChannel) {
        this.payChannel = payChannel == null ? null : payChannel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER.PAY_BILL_NO
     *
     * @return the value of CULSITE.ES_ORDER.PAY_BILL_NO
     *
     * @mbggenerated
     */
    public String getPayBillNo() {
        return payBillNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER.PAY_BILL_NO
     *
     * @param payBillNo the value for CULSITE.ES_ORDER.PAY_BILL_NO
     *
     * @mbggenerated
     */
    public void setPayBillNo(String payBillNo) {
        this.payBillNo = payBillNo == null ? null : payBillNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER.BUYER_MOBILE
     *
     * @return the value of CULSITE.ES_ORDER.BUYER_MOBILE
     *
     * @mbggenerated
     */
    public String getBuyerMobile() {
        return buyerMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER.BUYER_MOBILE
     *
     * @param buyerMobile the value for CULSITE.ES_ORDER.BUYER_MOBILE
     *
     * @mbggenerated
     */
    public void setBuyerMobile(String buyerMobile) {
        this.buyerMobile = buyerMobile == null ? null : buyerMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER.SENDER_NAME
     *
     * @return the value of CULSITE.ES_ORDER.SENDER_NAME
     *
     * @mbggenerated
     */
    public String getSenderName() {
        return senderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER.SENDER_NAME
     *
     * @param senderName the value for CULSITE.ES_ORDER.SENDER_NAME
     *
     * @mbggenerated
     */
    public void setSenderName(String senderName) {
        this.senderName = senderName == null ? null : senderName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER.SEND_WORD
     *
     * @return the value of CULSITE.ES_ORDER.SEND_WORD
     *
     * @mbggenerated
     */
    public String getSendWord() {
        return sendWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER.SEND_WORD
     *
     * @param sendWord the value for CULSITE.ES_ORDER.SEND_WORD
     *
     * @mbggenerated
     */
    public void setSendWord(String sendWord) {
        this.sendWord = sendWord == null ? null : sendWord.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER.EO_TYPE
     *
     * @return the value of CULSITE.ES_ORDER.EO_TYPE
     *
     * @mbggenerated
     */
    public String getEoType() {
        return eoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER.EO_TYPE
     *
     * @param eoType the value for CULSITE.ES_ORDER.EO_TYPE
     *
     * @mbggenerated
     */
    public void setEoType(String eoType) {
        this.eoType = eoType == null ? null : eoType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER.CUST_SEQ
     *
     * @return the value of CULSITE.ES_ORDER.CUST_SEQ
     *
     * @mbggenerated
     */
    public String getCustSeq() {
        return custSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER.CUST_SEQ
     *
     * @param custSeq the value for CULSITE.ES_ORDER.CUST_SEQ
     *
     * @mbggenerated
     */
    public void setCustSeq(String custSeq) {
        this.custSeq = custSeq == null ? null : custSeq.trim();
    }
}