package com.opvita.activity.dto;

import java.math.BigDecimal;

public class EsOrderItemsDTO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER_ITEMS.ITEM_ID
     *
     * @mbggenerated
     */
    private Integer itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER_ITEMS.ORDER_ID
     *
     * @mbggenerated
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER_ITEMS.GOODS_ID
     *
     * @mbggenerated
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER_ITEMS.PRODUCT_ID
     *
     * @mbggenerated
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER_ITEMS.CAT_ID
     *
     * @mbggenerated
     */
    private Integer catId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER_ITEMS.NUM
     *
     * @mbggenerated
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER_ITEMS.SHIP_NUM
     *
     * @mbggenerated
     */
    private Integer shipNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER_ITEMS.SN
     *
     * @mbggenerated
     */
    private String sn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER_ITEMS.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER_ITEMS.PRICE
     *
     * @mbggenerated
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER_ITEMS.GAINEDPOINT
     *
     * @mbggenerated
     */
    private Long gainedpoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER_ITEMS.STATE
     *
     * @mbggenerated
     */
    private Short state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER_ITEMS.CHANGE_GOODS_NAME
     *
     * @mbggenerated
     */
    private String changeGoodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER_ITEMS.CHANGE_GOODS_ID
     *
     * @mbggenerated
     */
    private Integer changeGoodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.ES_ORDER_ITEMS.UNIT
     *
     * @mbggenerated
     */
    private String unit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER_ITEMS.ITEM_ID
     *
     * @return the value of CULSITE.ES_ORDER_ITEMS.ITEM_ID
     *
     * @mbggenerated
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER_ITEMS.ITEM_ID
     *
     * @param itemId the value for CULSITE.ES_ORDER_ITEMS.ITEM_ID
     *
     * @mbggenerated
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER_ITEMS.ORDER_ID
     *
     * @return the value of CULSITE.ES_ORDER_ITEMS.ORDER_ID
     *
     * @mbggenerated
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER_ITEMS.ORDER_ID
     *
     * @param orderId the value for CULSITE.ES_ORDER_ITEMS.ORDER_ID
     *
     * @mbggenerated
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER_ITEMS.GOODS_ID
     *
     * @return the value of CULSITE.ES_ORDER_ITEMS.GOODS_ID
     *
     * @mbggenerated
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER_ITEMS.GOODS_ID
     *
     * @param goodsId the value for CULSITE.ES_ORDER_ITEMS.GOODS_ID
     *
     * @mbggenerated
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER_ITEMS.PRODUCT_ID
     *
     * @return the value of CULSITE.ES_ORDER_ITEMS.PRODUCT_ID
     *
     * @mbggenerated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER_ITEMS.PRODUCT_ID
     *
     * @param productId the value for CULSITE.ES_ORDER_ITEMS.PRODUCT_ID
     *
     * @mbggenerated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER_ITEMS.CAT_ID
     *
     * @return the value of CULSITE.ES_ORDER_ITEMS.CAT_ID
     *
     * @mbggenerated
     */
    public Integer getCatId() {
        return catId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER_ITEMS.CAT_ID
     *
     * @param catId the value for CULSITE.ES_ORDER_ITEMS.CAT_ID
     *
     * @mbggenerated
     */
    public void setCatId(Integer catId) {
        this.catId = catId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER_ITEMS.NUM
     *
     * @return the value of CULSITE.ES_ORDER_ITEMS.NUM
     *
     * @mbggenerated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER_ITEMS.NUM
     *
     * @param num the value for CULSITE.ES_ORDER_ITEMS.NUM
     *
     * @mbggenerated
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER_ITEMS.SHIP_NUM
     *
     * @return the value of CULSITE.ES_ORDER_ITEMS.SHIP_NUM
     *
     * @mbggenerated
     */
    public Integer getShipNum() {
        return shipNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER_ITEMS.SHIP_NUM
     *
     * @param shipNum the value for CULSITE.ES_ORDER_ITEMS.SHIP_NUM
     *
     * @mbggenerated
     */
    public void setShipNum(Integer shipNum) {
        this.shipNum = shipNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER_ITEMS.SN
     *
     * @return the value of CULSITE.ES_ORDER_ITEMS.SN
     *
     * @mbggenerated
     */
    public String getSn() {
        return sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER_ITEMS.SN
     *
     * @param sn the value for CULSITE.ES_ORDER_ITEMS.SN
     *
     * @mbggenerated
     */
    public void setSn(String sn) {
        this.sn = sn == null ? null : sn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER_ITEMS.NAME
     *
     * @return the value of CULSITE.ES_ORDER_ITEMS.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER_ITEMS.NAME
     *
     * @param name the value for CULSITE.ES_ORDER_ITEMS.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER_ITEMS.PRICE
     *
     * @return the value of CULSITE.ES_ORDER_ITEMS.PRICE
     *
     * @mbggenerated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER_ITEMS.PRICE
     *
     * @param price the value for CULSITE.ES_ORDER_ITEMS.PRICE
     *
     * @mbggenerated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER_ITEMS.GAINEDPOINT
     *
     * @return the value of CULSITE.ES_ORDER_ITEMS.GAINEDPOINT
     *
     * @mbggenerated
     */
    public Long getGainedpoint() {
        return gainedpoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER_ITEMS.GAINEDPOINT
     *
     * @param gainedpoint the value for CULSITE.ES_ORDER_ITEMS.GAINEDPOINT
     *
     * @mbggenerated
     */
    public void setGainedpoint(Long gainedpoint) {
        this.gainedpoint = gainedpoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER_ITEMS.STATE
     *
     * @return the value of CULSITE.ES_ORDER_ITEMS.STATE
     *
     * @mbggenerated
     */
    public Short getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER_ITEMS.STATE
     *
     * @param state the value for CULSITE.ES_ORDER_ITEMS.STATE
     *
     * @mbggenerated
     */
    public void setState(Short state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER_ITEMS.CHANGE_GOODS_NAME
     *
     * @return the value of CULSITE.ES_ORDER_ITEMS.CHANGE_GOODS_NAME
     *
     * @mbggenerated
     */
    public String getChangeGoodsName() {
        return changeGoodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER_ITEMS.CHANGE_GOODS_NAME
     *
     * @param changeGoodsName the value for CULSITE.ES_ORDER_ITEMS.CHANGE_GOODS_NAME
     *
     * @mbggenerated
     */
    public void setChangeGoodsName(String changeGoodsName) {
        this.changeGoodsName = changeGoodsName == null ? null : changeGoodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER_ITEMS.CHANGE_GOODS_ID
     *
     * @return the value of CULSITE.ES_ORDER_ITEMS.CHANGE_GOODS_ID
     *
     * @mbggenerated
     */
    public Integer getChangeGoodsId() {
        return changeGoodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER_ITEMS.CHANGE_GOODS_ID
     *
     * @param changeGoodsId the value for CULSITE.ES_ORDER_ITEMS.CHANGE_GOODS_ID
     *
     * @mbggenerated
     */
    public void setChangeGoodsId(Integer changeGoodsId) {
        this.changeGoodsId = changeGoodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.ES_ORDER_ITEMS.UNIT
     *
     * @return the value of CULSITE.ES_ORDER_ITEMS.UNIT
     *
     * @mbggenerated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.ES_ORDER_ITEMS.UNIT
     *
     * @param unit the value for CULSITE.ES_ORDER_ITEMS.UNIT
     *
     * @mbggenerated
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }
}