package com.opvita.activity.dto;

import java.math.BigDecimal;
import java.util.Date;

public class MActivityDTO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_ACTIVITY.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_ACTIVITY.ISSUER_ID
     *
     * @mbggenerated
     */
    private String issuerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_ACTIVITY.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_ACTIVITY.VALID_START
     *
     * @mbggenerated
     */
    private Date validStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_ACTIVITY.VALID_END
     *
     * @mbggenerated
     */
    private Date validEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_ACTIVITY.MUTEX
     *
     * @mbggenerated
     */
    private String mutex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_ACTIVITY.PRIORITY
     *
     * @mbggenerated
     */
    private BigDecimal priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_ACTIVITY.CHANNEL
     *
     * @mbggenerated
     */
    private String channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_ACTIVITY.CREATE_USER
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_ACTIVITY.CREATE_TIMESTAMP
     *
     * @mbggenerated
     */
    private Date createTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_ACTIVITY.UPDATE_USER
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_ACTIVITY.UPDATE_TIMESTAMP
     *
     * @mbggenerated
     */
    private Date updateTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_ACTIVITY.TITLE
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_ACTIVITY.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_ACTIVITY.ID
     *
     * @return the value of M_ACTIVITY.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_ACTIVITY.ID
     *
     * @param id the value for M_ACTIVITY.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_ACTIVITY.ISSUER_ID
     *
     * @return the value of M_ACTIVITY.ISSUER_ID
     *
     * @mbggenerated
     */
    public String getIssuerId() {
        return issuerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_ACTIVITY.ISSUER_ID
     *
     * @param issuerId the value for M_ACTIVITY.ISSUER_ID
     *
     * @mbggenerated
     */
    public void setIssuerId(String issuerId) {
        this.issuerId = issuerId == null ? null : issuerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_ACTIVITY.STATUS
     *
     * @return the value of M_ACTIVITY.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_ACTIVITY.STATUS
     *
     * @param status the value for M_ACTIVITY.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_ACTIVITY.VALID_START
     *
     * @return the value of M_ACTIVITY.VALID_START
     *
     * @mbggenerated
     */
    public Date getValidStart() {
        return validStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_ACTIVITY.VALID_START
     *
     * @param validStart the value for M_ACTIVITY.VALID_START
     *
     * @mbggenerated
     */
    public void setValidStart(Date validStart) {
        this.validStart = validStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_ACTIVITY.VALID_END
     *
     * @return the value of M_ACTIVITY.VALID_END
     *
     * @mbggenerated
     */
    public Date getValidEnd() {
        return validEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_ACTIVITY.VALID_END
     *
     * @param validEnd the value for M_ACTIVITY.VALID_END
     *
     * @mbggenerated
     */
    public void setValidEnd(Date validEnd) {
        this.validEnd = validEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_ACTIVITY.MUTEX
     *
     * @return the value of M_ACTIVITY.MUTEX
     *
     * @mbggenerated
     */
    public String getMutex() {
        return mutex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_ACTIVITY.MUTEX
     *
     * @param mutex the value for M_ACTIVITY.MUTEX
     *
     * @mbggenerated
     */
    public void setMutex(String mutex) {
        this.mutex = mutex == null ? null : mutex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_ACTIVITY.PRIORITY
     *
     * @return the value of M_ACTIVITY.PRIORITY
     *
     * @mbggenerated
     */
    public BigDecimal getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_ACTIVITY.PRIORITY
     *
     * @param priority the value for M_ACTIVITY.PRIORITY
     *
     * @mbggenerated
     */
    public void setPriority(BigDecimal priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_ACTIVITY.CHANNEL
     *
     * @return the value of M_ACTIVITY.CHANNEL
     *
     * @mbggenerated
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_ACTIVITY.CHANNEL
     *
     * @param channel the value for M_ACTIVITY.CHANNEL
     *
     * @mbggenerated
     */
    public void setChannel(String channel) {
        this.channel = channel == null ? null : channel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_ACTIVITY.CREATE_USER
     *
     * @return the value of M_ACTIVITY.CREATE_USER
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_ACTIVITY.CREATE_USER
     *
     * @param createUser the value for M_ACTIVITY.CREATE_USER
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_ACTIVITY.CREATE_TIMESTAMP
     *
     * @return the value of M_ACTIVITY.CREATE_TIMESTAMP
     *
     * @mbggenerated
     */
    public Date getCreateTimestamp() {
        return createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_ACTIVITY.CREATE_TIMESTAMP
     *
     * @param createTimestamp the value for M_ACTIVITY.CREATE_TIMESTAMP
     *
     * @mbggenerated
     */
    public void setCreateTimestamp(Date createTimestamp) {
        this.createTimestamp = createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_ACTIVITY.UPDATE_USER
     *
     * @return the value of M_ACTIVITY.UPDATE_USER
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_ACTIVITY.UPDATE_USER
     *
     * @param updateUser the value for M_ACTIVITY.UPDATE_USER
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_ACTIVITY.UPDATE_TIMESTAMP
     *
     * @return the value of M_ACTIVITY.UPDATE_TIMESTAMP
     *
     * @mbggenerated
     */
    public Date getUpdateTimestamp() {
        return updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_ACTIVITY.UPDATE_TIMESTAMP
     *
     * @param updateTimestamp the value for M_ACTIVITY.UPDATE_TIMESTAMP
     *
     * @mbggenerated
     */
    public void setUpdateTimestamp(Date updateTimestamp) {
        this.updateTimestamp = updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_ACTIVITY.TITLE
     *
     * @return the value of M_ACTIVITY.TITLE
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_ACTIVITY.TITLE
     *
     * @param title the value for M_ACTIVITY.TITLE
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_ACTIVITY.REMARK
     *
     * @return the value of M_ACTIVITY.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_ACTIVITY.REMARK
     *
     * @param remark the value for M_ACTIVITY.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}