package com.opvita.activity.dto;

import java.util.Date;

public class MProductInventoryDTO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_PRODUCT_INVENTORY.MPI_ID
     *
     * @mbggenerated
     */
    private String mpiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_PRODUCT_INVENTORY.MPI_PRODUCT_ID
     *
     * @mbggenerated
     */
    private String mpiProductId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_PRODUCT_INVENTORY.MPI_STORE
     *
     * @mbggenerated
     */
    private Long mpiStore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_PRODUCT_INVENTORY.MPI_SALE_NUM
     *
     * @mbggenerated
     */
    private Long mpiSaleNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_PRODUCT_INVENTORY.CREATE_USER
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_PRODUCT_INVENTORY.UPDATE_USER
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_PRODUCT_INVENTORY.CREATE_TIMESTAMP
     *
     * @mbggenerated
     */
    private Date createTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_PRODUCT_INVENTORY.UPDATE_TIMESTAMP
     *
     * @mbggenerated
     */
    private Date updateTimestamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_PRODUCT_INVENTORY.MPI_ID
     *
     * @return the value of CULSITE.M_PRODUCT_INVENTORY.MPI_ID
     *
     * @mbggenerated
     */
    public String getMpiId() {
        return mpiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_PRODUCT_INVENTORY.MPI_ID
     *
     * @param mpiId the value for CULSITE.M_PRODUCT_INVENTORY.MPI_ID
     *
     * @mbggenerated
     */
    public void setMpiId(String mpiId) {
        this.mpiId = mpiId == null ? null : mpiId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_PRODUCT_INVENTORY.MPI_PRODUCT_ID
     *
     * @return the value of CULSITE.M_PRODUCT_INVENTORY.MPI_PRODUCT_ID
     *
     * @mbggenerated
     */
    public String getMpiProductId() {
        return mpiProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_PRODUCT_INVENTORY.MPI_PRODUCT_ID
     *
     * @param mpiProductId the value for CULSITE.M_PRODUCT_INVENTORY.MPI_PRODUCT_ID
     *
     * @mbggenerated
     */
    public void setMpiProductId(String mpiProductId) {
        this.mpiProductId = mpiProductId == null ? null : mpiProductId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_PRODUCT_INVENTORY.MPI_STORE
     *
     * @return the value of CULSITE.M_PRODUCT_INVENTORY.MPI_STORE
     *
     * @mbggenerated
     */
    public Long getMpiStore() {
        return mpiStore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_PRODUCT_INVENTORY.MPI_STORE
     *
     * @param mpiStore the value for CULSITE.M_PRODUCT_INVENTORY.MPI_STORE
     *
     * @mbggenerated
     */
    public void setMpiStore(Long mpiStore) {
        this.mpiStore = mpiStore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_PRODUCT_INVENTORY.MPI_SALE_NUM
     *
     * @return the value of CULSITE.M_PRODUCT_INVENTORY.MPI_SALE_NUM
     *
     * @mbggenerated
     */
    public Long getMpiSaleNum() {
        return mpiSaleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_PRODUCT_INVENTORY.MPI_SALE_NUM
     *
     * @param mpiSaleNum the value for CULSITE.M_PRODUCT_INVENTORY.MPI_SALE_NUM
     *
     * @mbggenerated
     */
    public void setMpiSaleNum(Long mpiSaleNum) {
        this.mpiSaleNum = mpiSaleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_PRODUCT_INVENTORY.CREATE_USER
     *
     * @return the value of CULSITE.M_PRODUCT_INVENTORY.CREATE_USER
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_PRODUCT_INVENTORY.CREATE_USER
     *
     * @param createUser the value for CULSITE.M_PRODUCT_INVENTORY.CREATE_USER
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_PRODUCT_INVENTORY.UPDATE_USER
     *
     * @return the value of CULSITE.M_PRODUCT_INVENTORY.UPDATE_USER
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_PRODUCT_INVENTORY.UPDATE_USER
     *
     * @param updateUser the value for CULSITE.M_PRODUCT_INVENTORY.UPDATE_USER
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_PRODUCT_INVENTORY.CREATE_TIMESTAMP
     *
     * @return the value of CULSITE.M_PRODUCT_INVENTORY.CREATE_TIMESTAMP
     *
     * @mbggenerated
     */
    public Date getCreateTimestamp() {
        return createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_PRODUCT_INVENTORY.CREATE_TIMESTAMP
     *
     * @param createTimestamp the value for CULSITE.M_PRODUCT_INVENTORY.CREATE_TIMESTAMP
     *
     * @mbggenerated
     */
    public void setCreateTimestamp(Date createTimestamp) {
        this.createTimestamp = createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_PRODUCT_INVENTORY.UPDATE_TIMESTAMP
     *
     * @return the value of CULSITE.M_PRODUCT_INVENTORY.UPDATE_TIMESTAMP
     *
     * @mbggenerated
     */
    public Date getUpdateTimestamp() {
        return updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_PRODUCT_INVENTORY.UPDATE_TIMESTAMP
     *
     * @param updateTimestamp the value for CULSITE.M_PRODUCT_INVENTORY.UPDATE_TIMESTAMP
     *
     * @mbggenerated
     */
    public void setUpdateTimestamp(Date updateTimestamp) {
        this.updateTimestamp = updateTimestamp;
    }
}