package com.opvita.activity.dto;

import java.util.Date;

public class MProductInfoDTO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_PRODUCT_INFO.PRODUCT_ID
     *
     * @mbggenerated
     */
    private String productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_PRODUCT_INFO.PRODUCT_NAME
     *
     * @mbggenerated
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_PRODUCT_INFO.ISSUER_ID
     *
     * @mbggenerated
     */
    private String issuerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_PRODUCT_INFO.FIX_FLAG
     *
     * @mbggenerated
     */
    private String fixFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_PRODUCT_INFO.CARD_PRICE
     *
     * @mbggenerated
     */
    private Long cardPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_PRODUCT_INFO.DESCRIBE
     *
     * @mbggenerated
     */
    private String describe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_PRODUCT_INFO.CREATE_USER
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_PRODUCT_INFO.CREATE_TIMESTAMP
     *
     * @mbggenerated
     */
    private Date createTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_PRODUCT_INFO.UPDATE_USER
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_PRODUCT_INFO.UPDATE_TIMESTAMP
     *
     * @mbggenerated
     */
    private Date updateTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_PRODUCT_INFO.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_PRODUCT_INFO.SALE_LIMIT
     *
     * @mbggenerated
     */
    private Long saleLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_PRODUCT_INFO.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_PRODUCT_INFO.PRODUCT_ID
     *
     * @return the value of CULSITE.M_PRODUCT_INFO.PRODUCT_ID
     *
     * @mbggenerated
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_PRODUCT_INFO.PRODUCT_ID
     *
     * @param productId the value for CULSITE.M_PRODUCT_INFO.PRODUCT_ID
     *
     * @mbggenerated
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_PRODUCT_INFO.PRODUCT_NAME
     *
     * @return the value of CULSITE.M_PRODUCT_INFO.PRODUCT_NAME
     *
     * @mbggenerated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_PRODUCT_INFO.PRODUCT_NAME
     *
     * @param productName the value for CULSITE.M_PRODUCT_INFO.PRODUCT_NAME
     *
     * @mbggenerated
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_PRODUCT_INFO.ISSUER_ID
     *
     * @return the value of CULSITE.M_PRODUCT_INFO.ISSUER_ID
     *
     * @mbggenerated
     */
    public String getIssuerId() {
        return issuerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_PRODUCT_INFO.ISSUER_ID
     *
     * @param issuerId the value for CULSITE.M_PRODUCT_INFO.ISSUER_ID
     *
     * @mbggenerated
     */
    public void setIssuerId(String issuerId) {
        this.issuerId = issuerId == null ? null : issuerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_PRODUCT_INFO.FIX_FLAG
     *
     * @return the value of CULSITE.M_PRODUCT_INFO.FIX_FLAG
     *
     * @mbggenerated
     */
    public String getFixFlag() {
        return fixFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_PRODUCT_INFO.FIX_FLAG
     *
     * @param fixFlag the value for CULSITE.M_PRODUCT_INFO.FIX_FLAG
     *
     * @mbggenerated
     */
    public void setFixFlag(String fixFlag) {
        this.fixFlag = fixFlag == null ? null : fixFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_PRODUCT_INFO.CARD_PRICE
     *
     * @return the value of CULSITE.M_PRODUCT_INFO.CARD_PRICE
     *
     * @mbggenerated
     */
    public Long getCardPrice() {
        return cardPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_PRODUCT_INFO.CARD_PRICE
     *
     * @param cardPrice the value for CULSITE.M_PRODUCT_INFO.CARD_PRICE
     *
     * @mbggenerated
     */
    public void setCardPrice(Long cardPrice) {
        this.cardPrice = cardPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_PRODUCT_INFO.DESCRIBE
     *
     * @return the value of CULSITE.M_PRODUCT_INFO.DESCRIBE
     *
     * @mbggenerated
     */
    public String getDescribe() {
        return describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_PRODUCT_INFO.DESCRIBE
     *
     * @param describe the value for CULSITE.M_PRODUCT_INFO.DESCRIBE
     *
     * @mbggenerated
     */
    public void setDescribe(String describe) {
        this.describe = describe == null ? null : describe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_PRODUCT_INFO.CREATE_USER
     *
     * @return the value of CULSITE.M_PRODUCT_INFO.CREATE_USER
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_PRODUCT_INFO.CREATE_USER
     *
     * @param createUser the value for CULSITE.M_PRODUCT_INFO.CREATE_USER
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_PRODUCT_INFO.CREATE_TIMESTAMP
     *
     * @return the value of CULSITE.M_PRODUCT_INFO.CREATE_TIMESTAMP
     *
     * @mbggenerated
     */
    public Date getCreateTimestamp() {
        return createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_PRODUCT_INFO.CREATE_TIMESTAMP
     *
     * @param createTimestamp the value for CULSITE.M_PRODUCT_INFO.CREATE_TIMESTAMP
     *
     * @mbggenerated
     */
    public void setCreateTimestamp(Date createTimestamp) {
        this.createTimestamp = createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_PRODUCT_INFO.UPDATE_USER
     *
     * @return the value of CULSITE.M_PRODUCT_INFO.UPDATE_USER
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_PRODUCT_INFO.UPDATE_USER
     *
     * @param updateUser the value for CULSITE.M_PRODUCT_INFO.UPDATE_USER
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_PRODUCT_INFO.UPDATE_TIMESTAMP
     *
     * @return the value of CULSITE.M_PRODUCT_INFO.UPDATE_TIMESTAMP
     *
     * @mbggenerated
     */
    public Date getUpdateTimestamp() {
        return updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_PRODUCT_INFO.UPDATE_TIMESTAMP
     *
     * @param updateTimestamp the value for CULSITE.M_PRODUCT_INFO.UPDATE_TIMESTAMP
     *
     * @mbggenerated
     */
    public void setUpdateTimestamp(Date updateTimestamp) {
        this.updateTimestamp = updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_PRODUCT_INFO.REMARK
     *
     * @return the value of CULSITE.M_PRODUCT_INFO.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_PRODUCT_INFO.REMARK
     *
     * @param remark the value for CULSITE.M_PRODUCT_INFO.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_PRODUCT_INFO.SALE_LIMIT
     *
     * @return the value of CULSITE.M_PRODUCT_INFO.SALE_LIMIT
     *
     * @mbggenerated
     */
    public Long getSaleLimit() {
        return saleLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_PRODUCT_INFO.SALE_LIMIT
     *
     * @param saleLimit the value for CULSITE.M_PRODUCT_INFO.SALE_LIMIT
     *
     * @mbggenerated
     */
    public void setSaleLimit(Long saleLimit) {
        this.saleLimit = saleLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_PRODUCT_INFO.STATUS
     *
     * @return the value of CULSITE.M_PRODUCT_INFO.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_PRODUCT_INFO.STATUS
     *
     * @param status the value for CULSITE.M_PRODUCT_INFO.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}