package com.opvita.activity.dto;

import java.util.Date;

public class MRewardLogDTO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_REWARD_LOG.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_REWARD_LOG.USER_ID
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_REWARD_LOG.USER_MOBILE
     *
     * @mbggenerated
     */
    private String userMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_REWARD_LOG.ORDER_ID
     *
     * @mbggenerated
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_REWARD_LOG.ORDER_SN
     *
     * @mbggenerated
     */
    private String orderSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_REWARD_LOG.REWARD_ID
     *
     * @mbggenerated
     */
    private String rewardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_REWARD_LOG.RULE_ID
     *
     * @mbggenerated
     */
    private String ruleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_REWARD_LOG.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_REWARD_LOG.CREATE_USER
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_REWARD_LOG.CREATE_TIMESTAMP
     *
     * @mbggenerated
     */
    private Date createTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_REWARD_LOG.UPDATE_USER
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_REWARD_LOG.UPDATE_TIMESTAMP
     *
     * @mbggenerated
     */
    private Date updateTimestamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_REWARD_LOG.ID
     *
     * @return the value of M_REWARD_LOG.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_REWARD_LOG.ID
     *
     * @param id the value for M_REWARD_LOG.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_REWARD_LOG.USER_ID
     *
     * @return the value of M_REWARD_LOG.USER_ID
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_REWARD_LOG.USER_ID
     *
     * @param userId the value for M_REWARD_LOG.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_REWARD_LOG.USER_MOBILE
     *
     * @return the value of M_REWARD_LOG.USER_MOBILE
     *
     * @mbggenerated
     */
    public String getUserMobile() {
        return userMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_REWARD_LOG.USER_MOBILE
     *
     * @param userMobile the value for M_REWARD_LOG.USER_MOBILE
     *
     * @mbggenerated
     */
    public void setUserMobile(String userMobile) {
        this.userMobile = userMobile == null ? null : userMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_REWARD_LOG.ORDER_ID
     *
     * @return the value of M_REWARD_LOG.ORDER_ID
     *
     * @mbggenerated
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_REWARD_LOG.ORDER_ID
     *
     * @param orderId the value for M_REWARD_LOG.ORDER_ID
     *
     * @mbggenerated
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_REWARD_LOG.ORDER_SN
     *
     * @return the value of M_REWARD_LOG.ORDER_SN
     *
     * @mbggenerated
     */
    public String getOrderSn() {
        return orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_REWARD_LOG.ORDER_SN
     *
     * @param orderSn the value for M_REWARD_LOG.ORDER_SN
     *
     * @mbggenerated
     */
    public void setOrderSn(String orderSn) {
        this.orderSn = orderSn == null ? null : orderSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_REWARD_LOG.REWARD_ID
     *
     * @return the value of M_REWARD_LOG.REWARD_ID
     *
     * @mbggenerated
     */
    public String getRewardId() {
        return rewardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_REWARD_LOG.REWARD_ID
     *
     * @param rewardId the value for M_REWARD_LOG.REWARD_ID
     *
     * @mbggenerated
     */
    public void setRewardId(String rewardId) {
        this.rewardId = rewardId == null ? null : rewardId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_REWARD_LOG.RULE_ID
     *
     * @return the value of M_REWARD_LOG.RULE_ID
     *
     * @mbggenerated
     */
    public String getRuleId() {
        return ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_REWARD_LOG.RULE_ID
     *
     * @param ruleId the value for M_REWARD_LOG.RULE_ID
     *
     * @mbggenerated
     */
    public void setRuleId(String ruleId) {
        this.ruleId = ruleId == null ? null : ruleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_REWARD_LOG.STATUS
     *
     * @return the value of M_REWARD_LOG.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_REWARD_LOG.STATUS
     *
     * @param status the value for M_REWARD_LOG.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_REWARD_LOG.CREATE_USER
     *
     * @return the value of M_REWARD_LOG.CREATE_USER
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_REWARD_LOG.CREATE_USER
     *
     * @param createUser the value for M_REWARD_LOG.CREATE_USER
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_REWARD_LOG.CREATE_TIMESTAMP
     *
     * @return the value of M_REWARD_LOG.CREATE_TIMESTAMP
     *
     * @mbggenerated
     */
    public Date getCreateTimestamp() {
        return createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_REWARD_LOG.CREATE_TIMESTAMP
     *
     * @param createTimestamp the value for M_REWARD_LOG.CREATE_TIMESTAMP
     *
     * @mbggenerated
     */
    public void setCreateTimestamp(Date createTimestamp) {
        this.createTimestamp = createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_REWARD_LOG.UPDATE_USER
     *
     * @return the value of M_REWARD_LOG.UPDATE_USER
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_REWARD_LOG.UPDATE_USER
     *
     * @param updateUser the value for M_REWARD_LOG.UPDATE_USER
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_REWARD_LOG.UPDATE_TIMESTAMP
     *
     * @return the value of M_REWARD_LOG.UPDATE_TIMESTAMP
     *
     * @mbggenerated
     */
    public Date getUpdateTimestamp() {
        return updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_REWARD_LOG.UPDATE_TIMESTAMP
     *
     * @param updateTimestamp the value for M_REWARD_LOG.UPDATE_TIMESTAMP
     *
     * @mbggenerated
     */
    public void setUpdateTimestamp(Date updateTimestamp) {
        this.updateTimestamp = updateTimestamp;
    }
}