package com.opvita.activity.dto;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MRuleRewardDTOCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table M_RULE_REWARD
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table M_RULE_REWARD
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table M_RULE_REWARD
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_RULE_REWARD
     *
     * @mbggenerated
     */
    public MRuleRewardDTOCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_RULE_REWARD
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_RULE_REWARD
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_RULE_REWARD
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_RULE_REWARD
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_RULE_REWARD
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_RULE_REWARD
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_RULE_REWARD
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_RULE_REWARD
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_RULE_REWARD
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_RULE_REWARD
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table M_RULE_REWARD
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andRuleIdIsNull() {
            addCriterion("RULE_ID is null");
            return (Criteria) this;
        }

        public Criteria andRuleIdIsNotNull() {
            addCriterion("RULE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andRuleIdEqualTo(String value) {
            addCriterion("RULE_ID =", value, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleIdNotEqualTo(String value) {
            addCriterion("RULE_ID <>", value, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleIdGreaterThan(String value) {
            addCriterion("RULE_ID >", value, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleIdGreaterThanOrEqualTo(String value) {
            addCriterion("RULE_ID >=", value, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleIdLessThan(String value) {
            addCriterion("RULE_ID <", value, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleIdLessThanOrEqualTo(String value) {
            addCriterion("RULE_ID <=", value, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleIdLike(String value) {
            addCriterion("RULE_ID like", value, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleIdNotLike(String value) {
            addCriterion("RULE_ID not like", value, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleIdIn(List<String> values) {
            addCriterion("RULE_ID in", values, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleIdNotIn(List<String> values) {
            addCriterion("RULE_ID not in", values, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleIdBetween(String value1, String value2) {
            addCriterion("RULE_ID between", value1, value2, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleIdNotBetween(String value1, String value2) {
            addCriterion("RULE_ID not between", value1, value2, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRewardValueIsNull() {
            addCriterion("REWARD_VALUE is null");
            return (Criteria) this;
        }

        public Criteria andRewardValueIsNotNull() {
            addCriterion("REWARD_VALUE is not null");
            return (Criteria) this;
        }

        public Criteria andRewardValueEqualTo(Long value) {
            addCriterion("REWARD_VALUE =", value, "rewardValue");
            return (Criteria) this;
        }

        public Criteria andRewardValueNotEqualTo(Long value) {
            addCriterion("REWARD_VALUE <>", value, "rewardValue");
            return (Criteria) this;
        }

        public Criteria andRewardValueGreaterThan(Long value) {
            addCriterion("REWARD_VALUE >", value, "rewardValue");
            return (Criteria) this;
        }

        public Criteria andRewardValueGreaterThanOrEqualTo(Long value) {
            addCriterion("REWARD_VALUE >=", value, "rewardValue");
            return (Criteria) this;
        }

        public Criteria andRewardValueLessThan(Long value) {
            addCriterion("REWARD_VALUE <", value, "rewardValue");
            return (Criteria) this;
        }

        public Criteria andRewardValueLessThanOrEqualTo(Long value) {
            addCriterion("REWARD_VALUE <=", value, "rewardValue");
            return (Criteria) this;
        }

        public Criteria andRewardValueIn(List<Long> values) {
            addCriterion("REWARD_VALUE in", values, "rewardValue");
            return (Criteria) this;
        }

        public Criteria andRewardValueNotIn(List<Long> values) {
            addCriterion("REWARD_VALUE not in", values, "rewardValue");
            return (Criteria) this;
        }

        public Criteria andRewardValueBetween(Long value1, Long value2) {
            addCriterion("REWARD_VALUE between", value1, value2, "rewardValue");
            return (Criteria) this;
        }

        public Criteria andRewardValueNotBetween(Long value1, Long value2) {
            addCriterion("REWARD_VALUE not between", value1, value2, "rewardValue");
            return (Criteria) this;
        }

        public Criteria andRewardProductIsNull() {
            addCriterion("REWARD_PRODUCT is null");
            return (Criteria) this;
        }

        public Criteria andRewardProductIsNotNull() {
            addCriterion("REWARD_PRODUCT is not null");
            return (Criteria) this;
        }

        public Criteria andRewardProductEqualTo(String value) {
            addCriterion("REWARD_PRODUCT =", value, "rewardProduct");
            return (Criteria) this;
        }

        public Criteria andRewardProductNotEqualTo(String value) {
            addCriterion("REWARD_PRODUCT <>", value, "rewardProduct");
            return (Criteria) this;
        }

        public Criteria andRewardProductGreaterThan(String value) {
            addCriterion("REWARD_PRODUCT >", value, "rewardProduct");
            return (Criteria) this;
        }

        public Criteria andRewardProductGreaterThanOrEqualTo(String value) {
            addCriterion("REWARD_PRODUCT >=", value, "rewardProduct");
            return (Criteria) this;
        }

        public Criteria andRewardProductLessThan(String value) {
            addCriterion("REWARD_PRODUCT <", value, "rewardProduct");
            return (Criteria) this;
        }

        public Criteria andRewardProductLessThanOrEqualTo(String value) {
            addCriterion("REWARD_PRODUCT <=", value, "rewardProduct");
            return (Criteria) this;
        }

        public Criteria andRewardProductLike(String value) {
            addCriterion("REWARD_PRODUCT like", value, "rewardProduct");
            return (Criteria) this;
        }

        public Criteria andRewardProductNotLike(String value) {
            addCriterion("REWARD_PRODUCT not like", value, "rewardProduct");
            return (Criteria) this;
        }

        public Criteria andRewardProductIn(List<String> values) {
            addCriterion("REWARD_PRODUCT in", values, "rewardProduct");
            return (Criteria) this;
        }

        public Criteria andRewardProductNotIn(List<String> values) {
            addCriterion("REWARD_PRODUCT not in", values, "rewardProduct");
            return (Criteria) this;
        }

        public Criteria andRewardProductBetween(String value1, String value2) {
            addCriterion("REWARD_PRODUCT between", value1, value2, "rewardProduct");
            return (Criteria) this;
        }

        public Criteria andRewardProductNotBetween(String value1, String value2) {
            addCriterion("REWARD_PRODUCT not between", value1, value2, "rewardProduct");
            return (Criteria) this;
        }

        public Criteria andRewardTypeIsNull() {
            addCriterion("REWARD_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andRewardTypeIsNotNull() {
            addCriterion("REWARD_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andRewardTypeEqualTo(String value) {
            addCriterion("REWARD_TYPE =", value, "rewardType");
            return (Criteria) this;
        }

        public Criteria andRewardTypeNotEqualTo(String value) {
            addCriterion("REWARD_TYPE <>", value, "rewardType");
            return (Criteria) this;
        }

        public Criteria andRewardTypeGreaterThan(String value) {
            addCriterion("REWARD_TYPE >", value, "rewardType");
            return (Criteria) this;
        }

        public Criteria andRewardTypeGreaterThanOrEqualTo(String value) {
            addCriterion("REWARD_TYPE >=", value, "rewardType");
            return (Criteria) this;
        }

        public Criteria andRewardTypeLessThan(String value) {
            addCriterion("REWARD_TYPE <", value, "rewardType");
            return (Criteria) this;
        }

        public Criteria andRewardTypeLessThanOrEqualTo(String value) {
            addCriterion("REWARD_TYPE <=", value, "rewardType");
            return (Criteria) this;
        }

        public Criteria andRewardTypeLike(String value) {
            addCriterion("REWARD_TYPE like", value, "rewardType");
            return (Criteria) this;
        }

        public Criteria andRewardTypeNotLike(String value) {
            addCriterion("REWARD_TYPE not like", value, "rewardType");
            return (Criteria) this;
        }

        public Criteria andRewardTypeIn(List<String> values) {
            addCriterion("REWARD_TYPE in", values, "rewardType");
            return (Criteria) this;
        }

        public Criteria andRewardTypeNotIn(List<String> values) {
            addCriterion("REWARD_TYPE not in", values, "rewardType");
            return (Criteria) this;
        }

        public Criteria andRewardTypeBetween(String value1, String value2) {
            addCriterion("REWARD_TYPE between", value1, value2, "rewardType");
            return (Criteria) this;
        }

        public Criteria andRewardTypeNotBetween(String value1, String value2) {
            addCriterion("REWARD_TYPE not between", value1, value2, "rewardType");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("CREATE_USER is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("CREATE_USER is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("CREATE_USER =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("CREATE_USER <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("CREATE_USER >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_USER >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("CREATE_USER <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("CREATE_USER <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("CREATE_USER like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("CREATE_USER not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("CREATE_USER in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("CREATE_USER not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("CREATE_USER between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("CREATE_USER not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampIsNull() {
            addCriterion("CREATE_TIMESTAMP is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampIsNotNull() {
            addCriterion("CREATE_TIMESTAMP is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampEqualTo(Date value) {
            addCriterion("CREATE_TIMESTAMP =", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampNotEqualTo(Date value) {
            addCriterion("CREATE_TIMESTAMP <>", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampGreaterThan(Date value) {
            addCriterion("CREATE_TIMESTAMP >", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIMESTAMP >=", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampLessThan(Date value) {
            addCriterion("CREATE_TIMESTAMP <", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIMESTAMP <=", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampIn(List<Date> values) {
            addCriterion("CREATE_TIMESTAMP in", values, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampNotIn(List<Date> values) {
            addCriterion("CREATE_TIMESTAMP not in", values, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIMESTAMP between", value1, value2, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIMESTAMP not between", value1, value2, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNull() {
            addCriterion("UPDATE_USER is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNotNull() {
            addCriterion("UPDATE_USER is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserEqualTo(String value) {
            addCriterion("UPDATE_USER =", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotEqualTo(String value) {
            addCriterion("UPDATE_USER <>", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThan(String value) {
            addCriterion("UPDATE_USER >", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER >=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThan(String value) {
            addCriterion("UPDATE_USER <", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER <=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLike(String value) {
            addCriterion("UPDATE_USER like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotLike(String value) {
            addCriterion("UPDATE_USER not like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIn(List<String> values) {
            addCriterion("UPDATE_USER in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotIn(List<String> values) {
            addCriterion("UPDATE_USER not in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserBetween(String value1, String value2) {
            addCriterion("UPDATE_USER between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotBetween(String value1, String value2) {
            addCriterion("UPDATE_USER not between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampIsNull() {
            addCriterion("UPDATE_TIMESTAMP is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampIsNotNull() {
            addCriterion("UPDATE_TIMESTAMP is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampEqualTo(Date value) {
            addCriterion("UPDATE_TIMESTAMP =", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampNotEqualTo(Date value) {
            addCriterion("UPDATE_TIMESTAMP <>", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampGreaterThan(Date value) {
            addCriterion("UPDATE_TIMESTAMP >", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIMESTAMP >=", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampLessThan(Date value) {
            addCriterion("UPDATE_TIMESTAMP <", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIMESTAMP <=", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampIn(List<Date> values) {
            addCriterion("UPDATE_TIMESTAMP in", values, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampNotIn(List<Date> values) {
            addCriterion("UPDATE_TIMESTAMP not in", values, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIMESTAMP between", value1, value2, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIMESTAMP not between", value1, value2, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andMaxRewardsIsNull() {
            addCriterion("MAX_REWARDS is null");
            return (Criteria) this;
        }

        public Criteria andMaxRewardsIsNotNull() {
            addCriterion("MAX_REWARDS is not null");
            return (Criteria) this;
        }

        public Criteria andMaxRewardsEqualTo(Long value) {
            addCriterion("MAX_REWARDS =", value, "maxRewards");
            return (Criteria) this;
        }

        public Criteria andMaxRewardsNotEqualTo(Long value) {
            addCriterion("MAX_REWARDS <>", value, "maxRewards");
            return (Criteria) this;
        }

        public Criteria andMaxRewardsGreaterThan(Long value) {
            addCriterion("MAX_REWARDS >", value, "maxRewards");
            return (Criteria) this;
        }

        public Criteria andMaxRewardsGreaterThanOrEqualTo(Long value) {
            addCriterion("MAX_REWARDS >=", value, "maxRewards");
            return (Criteria) this;
        }

        public Criteria andMaxRewardsLessThan(Long value) {
            addCriterion("MAX_REWARDS <", value, "maxRewards");
            return (Criteria) this;
        }

        public Criteria andMaxRewardsLessThanOrEqualTo(Long value) {
            addCriterion("MAX_REWARDS <=", value, "maxRewards");
            return (Criteria) this;
        }

        public Criteria andMaxRewardsIn(List<Long> values) {
            addCriterion("MAX_REWARDS in", values, "maxRewards");
            return (Criteria) this;
        }

        public Criteria andMaxRewardsNotIn(List<Long> values) {
            addCriterion("MAX_REWARDS not in", values, "maxRewards");
            return (Criteria) this;
        }

        public Criteria andMaxRewardsBetween(Long value1, Long value2) {
            addCriterion("MAX_REWARDS between", value1, value2, "maxRewards");
            return (Criteria) this;
        }

        public Criteria andMaxRewardsNotBetween(Long value1, Long value2) {
            addCriterion("MAX_REWARDS not between", value1, value2, "maxRewards");
            return (Criteria) this;
        }

        public Criteria andCurrentRewardsIsNull() {
            addCriterion("CURRENT_REWARDS is null");
            return (Criteria) this;
        }

        public Criteria andCurrentRewardsIsNotNull() {
            addCriterion("CURRENT_REWARDS is not null");
            return (Criteria) this;
        }

        public Criteria andCurrentRewardsEqualTo(Long value) {
            addCriterion("CURRENT_REWARDS =", value, "currentRewards");
            return (Criteria) this;
        }

        public Criteria andCurrentRewardsNotEqualTo(Long value) {
            addCriterion("CURRENT_REWARDS <>", value, "currentRewards");
            return (Criteria) this;
        }

        public Criteria andCurrentRewardsGreaterThan(Long value) {
            addCriterion("CURRENT_REWARDS >", value, "currentRewards");
            return (Criteria) this;
        }

        public Criteria andCurrentRewardsGreaterThanOrEqualTo(Long value) {
            addCriterion("CURRENT_REWARDS >=", value, "currentRewards");
            return (Criteria) this;
        }

        public Criteria andCurrentRewardsLessThan(Long value) {
            addCriterion("CURRENT_REWARDS <", value, "currentRewards");
            return (Criteria) this;
        }

        public Criteria andCurrentRewardsLessThanOrEqualTo(Long value) {
            addCriterion("CURRENT_REWARDS <=", value, "currentRewards");
            return (Criteria) this;
        }

        public Criteria andCurrentRewardsIn(List<Long> values) {
            addCriterion("CURRENT_REWARDS in", values, "currentRewards");
            return (Criteria) this;
        }

        public Criteria andCurrentRewardsNotIn(List<Long> values) {
            addCriterion("CURRENT_REWARDS not in", values, "currentRewards");
            return (Criteria) this;
        }

        public Criteria andCurrentRewardsBetween(Long value1, Long value2) {
            addCriterion("CURRENT_REWARDS between", value1, value2, "currentRewards");
            return (Criteria) this;
        }

        public Criteria andCurrentRewardsNotBetween(Long value1, Long value2) {
            addCriterion("CURRENT_REWARDS not between", value1, value2, "currentRewards");
            return (Criteria) this;
        }

        public Criteria andRewardsPerPersonIsNull() {
            addCriterion("REWARDS_PER_PERSON is null");
            return (Criteria) this;
        }

        public Criteria andRewardsPerPersonIsNotNull() {
            addCriterion("REWARDS_PER_PERSON is not null");
            return (Criteria) this;
        }

        public Criteria andRewardsPerPersonEqualTo(Short value) {
            addCriterion("REWARDS_PER_PERSON =", value, "rewardsPerPerson");
            return (Criteria) this;
        }

        public Criteria andRewardsPerPersonNotEqualTo(Short value) {
            addCriterion("REWARDS_PER_PERSON <>", value, "rewardsPerPerson");
            return (Criteria) this;
        }

        public Criteria andRewardsPerPersonGreaterThan(Short value) {
            addCriterion("REWARDS_PER_PERSON >", value, "rewardsPerPerson");
            return (Criteria) this;
        }

        public Criteria andRewardsPerPersonGreaterThanOrEqualTo(Short value) {
            addCriterion("REWARDS_PER_PERSON >=", value, "rewardsPerPerson");
            return (Criteria) this;
        }

        public Criteria andRewardsPerPersonLessThan(Short value) {
            addCriterion("REWARDS_PER_PERSON <", value, "rewardsPerPerson");
            return (Criteria) this;
        }

        public Criteria andRewardsPerPersonLessThanOrEqualTo(Short value) {
            addCriterion("REWARDS_PER_PERSON <=", value, "rewardsPerPerson");
            return (Criteria) this;
        }

        public Criteria andRewardsPerPersonIn(List<Short> values) {
            addCriterion("REWARDS_PER_PERSON in", values, "rewardsPerPerson");
            return (Criteria) this;
        }

        public Criteria andRewardsPerPersonNotIn(List<Short> values) {
            addCriterion("REWARDS_PER_PERSON not in", values, "rewardsPerPerson");
            return (Criteria) this;
        }

        public Criteria andRewardsPerPersonBetween(Short value1, Short value2) {
            addCriterion("REWARDS_PER_PERSON between", value1, value2, "rewardsPerPerson");
            return (Criteria) this;
        }

        public Criteria andRewardsPerPersonNotBetween(Short value1, Short value2) {
            addCriterion("REWARDS_PER_PERSON not between", value1, value2, "rewardsPerPerson");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("STATUS like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("STATUS not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table M_RULE_REWARD
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table M_RULE_REWARD
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}