package com.opvita.activity.dto;

import java.util.Date;

public class MRuleParticipationDTO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_RULE_PARTICIPATION.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_RULE_PARTICIPATION.ACTIVITY_ID
     *
     * @mbggenerated
     */
    private String activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_RULE_PARTICIPATION.RULE_ID
     *
     * @mbggenerated
     */
    private String ruleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_RULE_PARTICIPATION.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_RULE_PARTICIPATION.CREATE_USER
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_RULE_PARTICIPATION.CREATE_TIMESTAMP
     *
     * @mbggenerated
     */
    private Date createTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_RULE_PARTICIPATION.UPDATE_USER
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_RULE_PARTICIPATION.UPDATE_TIMESTAMP
     *
     * @mbggenerated
     */
    private Date updateTimestamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_RULE_PARTICIPATION.ID
     *
     * @return the value of M_RULE_PARTICIPATION.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_RULE_PARTICIPATION.ID
     *
     * @param id the value for M_RULE_PARTICIPATION.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_RULE_PARTICIPATION.ACTIVITY_ID
     *
     * @return the value of M_RULE_PARTICIPATION.ACTIVITY_ID
     *
     * @mbggenerated
     */
    public String getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_RULE_PARTICIPATION.ACTIVITY_ID
     *
     * @param activityId the value for M_RULE_PARTICIPATION.ACTIVITY_ID
     *
     * @mbggenerated
     */
    public void setActivityId(String activityId) {
        this.activityId = activityId == null ? null : activityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_RULE_PARTICIPATION.RULE_ID
     *
     * @return the value of M_RULE_PARTICIPATION.RULE_ID
     *
     * @mbggenerated
     */
    public String getRuleId() {
        return ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_RULE_PARTICIPATION.RULE_ID
     *
     * @param ruleId the value for M_RULE_PARTICIPATION.RULE_ID
     *
     * @mbggenerated
     */
    public void setRuleId(String ruleId) {
        this.ruleId = ruleId == null ? null : ruleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_RULE_PARTICIPATION.STATUS
     *
     * @return the value of M_RULE_PARTICIPATION.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_RULE_PARTICIPATION.STATUS
     *
     * @param status the value for M_RULE_PARTICIPATION.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_RULE_PARTICIPATION.CREATE_USER
     *
     * @return the value of M_RULE_PARTICIPATION.CREATE_USER
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_RULE_PARTICIPATION.CREATE_USER
     *
     * @param createUser the value for M_RULE_PARTICIPATION.CREATE_USER
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_RULE_PARTICIPATION.CREATE_TIMESTAMP
     *
     * @return the value of M_RULE_PARTICIPATION.CREATE_TIMESTAMP
     *
     * @mbggenerated
     */
    public Date getCreateTimestamp() {
        return createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_RULE_PARTICIPATION.CREATE_TIMESTAMP
     *
     * @param createTimestamp the value for M_RULE_PARTICIPATION.CREATE_TIMESTAMP
     *
     * @mbggenerated
     */
    public void setCreateTimestamp(Date createTimestamp) {
        this.createTimestamp = createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_RULE_PARTICIPATION.UPDATE_USER
     *
     * @return the value of M_RULE_PARTICIPATION.UPDATE_USER
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_RULE_PARTICIPATION.UPDATE_USER
     *
     * @param updateUser the value for M_RULE_PARTICIPATION.UPDATE_USER
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_RULE_PARTICIPATION.UPDATE_TIMESTAMP
     *
     * @return the value of M_RULE_PARTICIPATION.UPDATE_TIMESTAMP
     *
     * @mbggenerated
     */
    public Date getUpdateTimestamp() {
        return updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_RULE_PARTICIPATION.UPDATE_TIMESTAMP
     *
     * @param updateTimestamp the value for M_RULE_PARTICIPATION.UPDATE_TIMESTAMP
     *
     * @mbggenerated
     */
    public void setUpdateTimestamp(Date updateTimestamp) {
        this.updateTimestamp = updateTimestamp;
    }
}