package com.opvita.activity.dto;

import java.util.Date;

public class MSaleProductDTO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_SALE_PRODUCT.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_SALE_PRODUCT.PRODUCT_ID
     *
     * @mbggenerated
     */
    private String productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_SALE_PRODUCT.SALE_PRICE
     *
     * @mbggenerated
     */
    private Long salePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_SALE_PRODUCT.RULE_ID
     *
     * @mbggenerated
     */
    private String ruleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_SALE_PRODUCT.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_SALE_PRODUCT.ISSUER_ID
     *
     * @mbggenerated
     */
    private String issuerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_SALE_PRODUCT.CREATE_USER
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_SALE_PRODUCT.CREATE_TIMESTAMP
     *
     * @mbggenerated
     */
    private Date createTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_SALE_PRODUCT.UPDATE_USER
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_SALE_PRODUCT.UPDATE_TIMESTAMP
     *
     * @mbggenerated
     */
    private Date updateTimestamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_SALE_PRODUCT.ID
     *
     * @return the value of M_SALE_PRODUCT.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_SALE_PRODUCT.ID
     *
     * @param id the value for M_SALE_PRODUCT.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_SALE_PRODUCT.PRODUCT_ID
     *
     * @return the value of M_SALE_PRODUCT.PRODUCT_ID
     *
     * @mbggenerated
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_SALE_PRODUCT.PRODUCT_ID
     *
     * @param productId the value for M_SALE_PRODUCT.PRODUCT_ID
     *
     * @mbggenerated
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_SALE_PRODUCT.SALE_PRICE
     *
     * @return the value of M_SALE_PRODUCT.SALE_PRICE
     *
     * @mbggenerated
     */
    public Long getSalePrice() {
        return salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_SALE_PRODUCT.SALE_PRICE
     *
     * @param salePrice the value for M_SALE_PRODUCT.SALE_PRICE
     *
     * @mbggenerated
     */
    public void setSalePrice(Long salePrice) {
        this.salePrice = salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_SALE_PRODUCT.RULE_ID
     *
     * @return the value of M_SALE_PRODUCT.RULE_ID
     *
     * @mbggenerated
     */
    public String getRuleId() {
        return ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_SALE_PRODUCT.RULE_ID
     *
     * @param ruleId the value for M_SALE_PRODUCT.RULE_ID
     *
     * @mbggenerated
     */
    public void setRuleId(String ruleId) {
        this.ruleId = ruleId == null ? null : ruleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_SALE_PRODUCT.STATUS
     *
     * @return the value of M_SALE_PRODUCT.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_SALE_PRODUCT.STATUS
     *
     * @param status the value for M_SALE_PRODUCT.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_SALE_PRODUCT.ISSUER_ID
     *
     * @return the value of M_SALE_PRODUCT.ISSUER_ID
     *
     * @mbggenerated
     */
    public String getIssuerId() {
        return issuerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_SALE_PRODUCT.ISSUER_ID
     *
     * @param issuerId the value for M_SALE_PRODUCT.ISSUER_ID
     *
     * @mbggenerated
     */
    public void setIssuerId(String issuerId) {
        this.issuerId = issuerId == null ? null : issuerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_SALE_PRODUCT.CREATE_USER
     *
     * @return the value of M_SALE_PRODUCT.CREATE_USER
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_SALE_PRODUCT.CREATE_USER
     *
     * @param createUser the value for M_SALE_PRODUCT.CREATE_USER
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_SALE_PRODUCT.CREATE_TIMESTAMP
     *
     * @return the value of M_SALE_PRODUCT.CREATE_TIMESTAMP
     *
     * @mbggenerated
     */
    public Date getCreateTimestamp() {
        return createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_SALE_PRODUCT.CREATE_TIMESTAMP
     *
     * @param createTimestamp the value for M_SALE_PRODUCT.CREATE_TIMESTAMP
     *
     * @mbggenerated
     */
    public void setCreateTimestamp(Date createTimestamp) {
        this.createTimestamp = createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_SALE_PRODUCT.UPDATE_USER
     *
     * @return the value of M_SALE_PRODUCT.UPDATE_USER
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_SALE_PRODUCT.UPDATE_USER
     *
     * @param updateUser the value for M_SALE_PRODUCT.UPDATE_USER
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_SALE_PRODUCT.UPDATE_TIMESTAMP
     *
     * @return the value of M_SALE_PRODUCT.UPDATE_TIMESTAMP
     *
     * @mbggenerated
     */
    public Date getUpdateTimestamp() {
        return updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_SALE_PRODUCT.UPDATE_TIMESTAMP
     *
     * @param updateTimestamp the value for M_SALE_PRODUCT.UPDATE_TIMESTAMP
     *
     * @mbggenerated
     */
    public void setUpdateTimestamp(Date updateTimestamp) {
        this.updateTimestamp = updateTimestamp;
    }
}