package com.opvita.activity.dao;

import com.opvita.activity.dto.EsOrderDTO;
import com.opvita.activity.dto.EsOrderDTOCriteria;
import com.opvita.activity.dto.EsOrderDTOWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EsOrderDTOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.ES_ORDER
     *
     * @mbggenerated
     */
    int countByExample(EsOrderDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.ES_ORDER
     *
     * @mbggenerated
     */
    int deleteByExample(EsOrderDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.ES_ORDER
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.ES_ORDER
     *
     * @mbggenerated
     */
    int insert(EsOrderDTOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.ES_ORDER
     *
     * @mbggenerated
     */
    int insertSelective(EsOrderDTOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.ES_ORDER
     *
     * @mbggenerated
     */
    List<EsOrderDTOWithBLOBs> selectByExampleWithBLOBs(EsOrderDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.ES_ORDER
     *
     * @mbggenerated
     */
    List<EsOrderDTO> selectByExample(EsOrderDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.ES_ORDER
     *
     * @mbggenerated
     */
    EsOrderDTOWithBLOBs selectByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.ES_ORDER
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") EsOrderDTOWithBLOBs record, @Param("example") EsOrderDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.ES_ORDER
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") EsOrderDTOWithBLOBs record, @Param("example") EsOrderDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.ES_ORDER
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") EsOrderDTO record, @Param("example") EsOrderDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.ES_ORDER
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EsOrderDTOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.ES_ORDER
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(EsOrderDTOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.ES_ORDER
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EsOrderDTO record);
}