package com.opvita.activity.dao;

import com.opvita.activity.dto.MActivityRuleDTO;
import com.opvita.activity.dto.MActivityRuleDTOCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MActivityRuleDTOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_ACTIVITY_RULE
     *
     * @mbggenerated
     */
    int countByExample(MActivityRuleDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_ACTIVITY_RULE
     *
     * @mbggenerated
     */
    int deleteByExample(MActivityRuleDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_ACTIVITY_RULE
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_ACTIVITY_RULE
     *
     * @mbggenerated
     */
    int insert(MActivityRuleDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_ACTIVITY_RULE
     *
     * @mbggenerated
     */
    int insertSelective(MActivityRuleDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_ACTIVITY_RULE
     *
     * @mbggenerated
     */
    List<MActivityRuleDTO> selectByExample(MActivityRuleDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_ACTIVITY_RULE
     *
     * @mbggenerated
     */
    MActivityRuleDTO selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_ACTIVITY_RULE
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MActivityRuleDTO record, @Param("example") MActivityRuleDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_ACTIVITY_RULE
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MActivityRuleDTO record, @Param("example") MActivityRuleDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_ACTIVITY_RULE
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MActivityRuleDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_ACTIVITY_RULE
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MActivityRuleDTO record);
}