package com.opvita.activity.dao;

import com.opvita.activity.dto.MProductInventoryDTO;
import com.opvita.activity.dto.MProductInventoryDTOCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MProductInventoryDTOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_PRODUCT_INVENTORY
     *
     * @mbggenerated
     */
    int countByExample(MProductInventoryDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_PRODUCT_INVENTORY
     *
     * @mbggenerated
     */
    int deleteByExample(MProductInventoryDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_PRODUCT_INVENTORY
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String mpiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_PRODUCT_INVENTORY
     *
     * @mbggenerated
     */
    int insert(MProductInventoryDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_PRODUCT_INVENTORY
     *
     * @mbggenerated
     */
    int insertSelective(MProductInventoryDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_PRODUCT_INVENTORY
     *
     * @mbggenerated
     */
    List<MProductInventoryDTO> selectByExample(MProductInventoryDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_PRODUCT_INVENTORY
     *
     * @mbggenerated
     */
    MProductInventoryDTO selectByPrimaryKey(String mpiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_PRODUCT_INVENTORY
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MProductInventoryDTO record, @Param("example") MProductInventoryDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_PRODUCT_INVENTORY
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MProductInventoryDTO record, @Param("example") MProductInventoryDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_PRODUCT_INVENTORY
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MProductInventoryDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_PRODUCT_INVENTORY
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MProductInventoryDTO record);
}