package com.opvita.activity.dao;

import com.opvita.activity.dto.MRewardLogDTO;
import com.opvita.activity.dto.MRewardLogDTOCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MRewardLogDTOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_REWARD_LOG
     *
     * @mbggenerated
     */
    int countByExample(MRewardLogDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_REWARD_LOG
     *
     * @mbggenerated
     */
    int deleteByExample(MRewardLogDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_REWARD_LOG
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_REWARD_LOG
     *
     * @mbggenerated
     */
    int insert(MRewardLogDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_REWARD_LOG
     *
     * @mbggenerated
     */
    int insertSelective(MRewardLogDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_REWARD_LOG
     *
     * @mbggenerated
     */
    List<MRewardLogDTO> selectByExample(MRewardLogDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_REWARD_LOG
     *
     * @mbggenerated
     */
    MRewardLogDTO selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_REWARD_LOG
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MRewardLogDTO record, @Param("example") MRewardLogDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_REWARD_LOG
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MRewardLogDTO record, @Param("example") MRewardLogDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_REWARD_LOG
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MRewardLogDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_REWARD_LOG
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MRewardLogDTO record);
}