package com.opvita.activity.dao;

import com.opvita.activity.dto.MRuleRewardDTO;
import com.opvita.activity.dto.MRuleRewardDTOCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MRuleRewardDTOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_RULE_REWARD
     *
     * @mbggenerated
     */
    int countByExample(MRuleRewardDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_RULE_REWARD
     *
     * @mbggenerated
     */
    int deleteByExample(MRuleRewardDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_RULE_REWARD
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_RULE_REWARD
     *
     * @mbggenerated
     */
    int insert(MRuleRewardDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_RULE_REWARD
     *
     * @mbggenerated
     */
    int insertSelective(MRuleRewardDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_RULE_REWARD
     *
     * @mbggenerated
     */
    List<MRuleRewardDTO> selectByExample(MRuleRewardDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_RULE_REWARD
     *
     * @mbggenerated
     */
    MRuleRewardDTO selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_RULE_REWARD
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MRuleRewardDTO record, @Param("example") MRuleRewardDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_RULE_REWARD
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MRuleRewardDTO record, @Param("example") MRuleRewardDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_RULE_REWARD
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MRuleRewardDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_RULE_REWARD
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MRuleRewardDTO record);
}